version: 0.1
phases:
    install:
        runtime-versions:
            nodejs: 12
    build:
        commands:
            - aws s3 sync ./  s3://meteor-website/  --delete  --region ap-northeast-2
artifacts:
    files:
        - "**/*"
    base-directory: ./
